# load libraries
message ('Load R packages')
packages = c('ggplot2',
    'Seurat',
    'dplyr',
    'Matrix',
    'ggpubr',
    'biomaRt',
    'gplots',
    'patchwork',
    'ComplexHeatmap',
    'RColorBrewer',
    'ggrepel',
    'fgsea',
    'tidyr',
    'gdata',
    'GSA',
    'DropletUtils', 
    'harmony',
    'scater',
    'destiny',
    'plotly',
    'GO.db', 
    'org.Mm.eg.db',
    'org.Hs.eg.db',
    'viridis',
    'BiocParallel',
    'ggridges',
    'clusterProfiler',
    'NMF',
    'WGCNA',
    'scWGCNA',
    'igraph',
    'tidyverse', 
    'paletteer',
    'rstatix',
    'data.table',
    'LSD', 
    'gridExtra',
    'muscat',
    'limma'
)
lapply(packages, require, character.only = TRUE)